version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    restart: always

  mute_api_server:
    build: ./api_server_v4
    container_name: mute_api_server
    ports:
      - 8088:8088
    restart: always
